open-telemetry/build-tools

semantic-conventions/requirements.txt
semantic-conventions/src/opentelemetry/semconv/model/utils.py
semantic-conventions/src/tests/conftest.py
semantic-conventions/src/tests/data/basic_example.md
semantic-conventions/src/tests/data/basic_example.yml
semantic-conventions/src/tests/data/semantic_attributes.yml
semantic-conventions/src/tests/data/semantic_attributes_deprecated.yml
semantic-conventions/src/tests/semconv/model/test_semantic_attribute.py
semantic-conventions/src/tests/semconv/model/test_semantic_convention.py
semantic-conventions/src/tests/semconv/model/test_utils.py
semantic-conventions/src/tests/semconv/templating/test_markdown.py

This PR adds unit tests to the semantic convention markdown/code generator. 
I was about to start working on refactoring this tool to add support for metrics semantic conventions, but I didn't want to get too far without at least a few unit tests, and I decided not to add all the unit tests in the same PR as the upcoming metrics work. 
So this PR should just be adding tests without changing any logic. 
There are two new directories of note:
* `semantic-conventions/src/tests`
This is the root directory for all of the tests. They're contained in the `semconv` subdirectory, and their package structure mirrors the library itself.
* `semantic-conventions/src/tests/data`
This directory contains test data files. Several yaml files, and one markdown. They are loaded into the tests using a pytest …

Semantic conventions tests

---

semantic-conventions/src/opentelemetry/semconv/main.py
semantic-conventions/src/opentelemetry/semconv/model/constraints.py
semantic-conventions/src/opentelemetry/semconv/model/semantic_attribute.py
semantic-conventions/src/opentelemetry/semconv/model/semantic_convention.py
semantic-conventions/src/opentelemetry/semconv/model/unit_member.py
semantic-conventions/src/opentelemetry/semconv/model/utils.py
semantic-conventions/src/opentelemetry/semconv/templating/code.py
semantic-conventions/src/opentelemetry/semconv/templating/markdown.py
semantic-conventions/src/tests/conftest.py
semantic-conventions/src/tests/data/jinja/metrics/expected.java
semantic-conventions/src/tests/data/jinja/metrics/units_template
semantic-conventions/src/tests/data/markdown/metrics/units_input.md
semantic-conventions/src/tests/data/markdown/metrics/units_output.md
semantic-conventions/src/tests/data/yaml/metrics/units.yaml
semantic-conventions/src/tests/semconv/model/test_correct_parse.py
semantic-conventions/src/tests/semconv/model/test_error_detection.py
semantic-conventions/src/tests/semconv/model/test_semantic_convention.py
semantic-conventions/src/tests/semconv/model/test_semantic_convention_units.py
semantic-conventions/src/tests/semconv/templating/test_code.py
semantic-conventions/src/tests/semconv/templating/test_markdown.py

This PR adds a new semantic convention type: units. 
There will only be the one table of units in the spec, but because we're expecting every language to create common constants for metric instrument units (see: [#1177](https://github.com/open-telemetry/opentelemetry-specification/pull/1177), I'd like to make it as easy as possible to generate the constants in code.
The unit yaml looks something like this:
```yaml
groups:
- id: units
type: units 
brief: Specification of commonly used units.
members:
- id: percent
brief: fraction of a total
value: "%"
- id: nanosecond
brief: time
value: NS
- id: connections
brief: connections
value: "{connections}"
```
And the resulting markdown looks like this:
| Name        | Kind of Quantity         | Unit String   |
| ------------| ---------------- …

Add unit semantic convention generator

---

.github/workflows/cpp_format_tools.yml
cpp_format_tools/Dockerfile
cpp_format_tools/README.md
cpp_format_tools/format.sh

To run the tools use:
`docker run --rm --privileged=true --volume ${PWD}:/otel cpp_format_tools:latest`
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

Add docker container for C++ format tools

---

.github/CODEOWNERS

@thisthat (part of `java-approvers`) initially developed the tool and @Oberon00 (`java-approvers` and `specs-trace-approvers`) is the second most experienced with it. They have also both reviewed almost all of the former PRs to this tool.

Add CODEOWNERS for the semantic conventions generator tool

---

semantic-conventions/CHANGELOG.md
semantic-conventions/src/opentelemetry/semconv/model/semantic_attribute.py
semantic-conventions/src/opentelemetry/semconv/version.py
semantic-conventions/src/tests/data/markdown/enum_int/expected.md
semantic-conventions/src/tests/data/markdown/enum_int/input.md
semantic-conventions/src/tests/data/markdown/enum_int/rpc.yaml
semantic-conventions/src/tests/data/yaml/errors/enum/enum_with_double_values.yaml
semantic-conventions/src/tests/semconv/model/test_error_detection.py
semantic-conventions/src/tests/semconv/templating/test_markdown.py

I just noticed that it still says `number` here:
https://github.com/open-telemetry/opentelemetry-specification/blob/b67faa4e0106cac194a837e3d419ae4fab9fc1c4/specification/trace/semantic_conventions/rpc.md#grpc-attributes

Fix markdown generator for int enums and add test

---

semantic-conventions/README.md
semantic-conventions/semconv.schema.json
semantic-conventions/syntax.md

As a follow-up I recommend removing the copy of `syntax.md` from https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/syntax.md and adapt the link in https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/README.md.
Logically, I think syntax.md needs to be here in the build-tools repository so we can update it in the same PR where we update something about the tool's input parsing (e.g. when adding new features).

Clean up docs, add syntax.md and semconv.schema.json

---

semantic-conventions/src/opentelemetry/semconv/model/semantic_attribute.py
semantic-conventions/src/opentelemetry/semconv/templating/markdown/__init__.py
semantic-conventions/src/opentelemetry/semconv/version.py
semantic-conventions/src/tests/data/markdown/multiple_enum/expected.md
semantic-conventions/src/tests/data/markdown/multiple_enum/general.yaml

Turns out #48 merely hid the actual problem which was that the YAML parser adds a trailing newline if you use `>` strings. Probably that is correct, but not what we expect in this context.
In other places we were already using `.strip()`, so also use it here.
This caused some broken formatting internally at Dynatrace where we also use this tool.
This commit also affects the `code` command, not only markdown.

Fix bug with newlines around enums.

---

semantic-conventions/syntax.md

This fixes a few issues with syntax.md:
- There was no update to syntax.md for
* https://github.com/open-telemetry/build-tools/pull/14 which added the "type" field
* https://github.com/open-telemetry/build-tools/pull/43 which added the "stability" field.
* This PR does NOT document the units type introduced in https://github.com/open-telemetry/build-tools/pull/21 (because I'm not familiar with it, maybe @justinfoote can create a follow-up).
- The `tag`, `deprecated` and `sampling_relevant` fields that the tool supported from the beginning were never documented.
- The description of `extends` was lacking.
The above was originally written by @thisthat, thank you!
- The relative link to the spec's attributes description broke after moving the tool here.
- Also, some minor formatting …

Update syntax.md with recent feature additions, document old features

---

semantic-conventions/CHANGELOG.md
semantic-conventions/semconv.schema.json
semantic-conventions/src/opentelemetry/semconv/main.py
semantic-conventions/src/opentelemetry/semconv/model/semantic_convention.py
semantic-conventions/src/opentelemetry/semconv/version.py
semantic-conventions/src/tests/data/markdown/event/event.yaml
semantic-conventions/src/tests/data/markdown/event/expected.md
semantic-conventions/src/tests/data/markdown/event/input.md
semantic-conventions/src/tests/data/yaml/errors/events/missing_event.yaml
semantic-conventions/src/tests/data/yaml/errors/events/no_event_type.yaml
semantic-conventions/src/tests/data/yaml/event.yaml
semantic-conventions/src/tests/data/yaml/span_event.yaml
semantic-conventions/src/tests/semconv/model/test_correct_parse.py
semantic-conventions/src/tests/semconv/model/test_error_detection.py
semantic-conventions/src/tests/semconv/templating/test_markdown.py
semantic-conventions/syntax.md

Event semantic conventions were designed with span events in mind but should be extendable to log events. See the new tests for how this can be useful to add a YAML definition for the exception semantic conventions in the spec.
This adds two new elements to the YAML definition:
* A new semantic convention type "event", with no additional fields
* A new additional field for "span" semantic conventions to reference associated event semantic conventions.
The generator validates that the semantic convention exists and the new data is available to the code templates,
but is not yet used in the markdown output.
It also updates the JSON schema to only allow span_kind and the new events field if the semantic convention type is not specified (defaults to span) or is "span". Unfortunately, we then …

Add support for Event Semantic Conventions

---

.github/workflows/semconvgen.yml
semantic-conventions/.flake8
semantic-conventions/.pylintrc
semantic-conventions/dev-requirements.txt
semantic-conventions/mypy.ini
semantic-conventions/setup.py
semantic-conventions/src/opentelemetry/semconv/main.py
semantic-conventions/src/opentelemetry/semconv/model/constraints.py
semantic-conventions/src/opentelemetry/semconv/model/exceptions.py
semantic-conventions/src/opentelemetry/semconv/model/semantic_attribute.py
semantic-conventions/src/opentelemetry/semconv/model/semantic_convention.py
semantic-conventions/src/opentelemetry/semconv/model/utils.py
semantic-conventions/src/opentelemetry/semconv/templating/code.py
semantic-conventions/src/opentelemetry/semconv/templating/markdown/__init__.py
semantic-conventions/src/tests/conftest.py
semantic-conventions/src/tests/semconv/model/test_correct_parse.py
semantic-conventions/src/tests/semconv/model/test_error_detection.py
semantic-conventions/src/tests/semconv/model/test_semantic_convention.py
semantic-conventions/src/tests/semconv/model/test_utils.py
semantic-conventions/src/tests/semconv/templating/test_code.py
semantic-conventions/src/tests/semconv/templating/test_markdown.py

This fixes errors from & runs the following linters, that are all also used in opentelemetry-python:
- flake8 (a fast & simple linter)
- pylint (a slow linter that does some code analysis)
- mypy (a checker for the type annotations we already had in place)

Run & fix linters flake8, pylint, mypy

---

.github/workflows/semconvgen.yml
semantic-conventions/dev-requirements.txt
semantic-conventions/setup.cfg
semantic-conventions/src/opentelemetry/semconv/main.py
semantic-conventions/src/opentelemetry/semconv/model/constraints.py
semantic-conventions/src/opentelemetry/semconv/model/semantic_attribute.py
semantic-conventions/src/opentelemetry/semconv/model/semantic_convention.py
semantic-conventions/src/opentelemetry/semconv/model/utils.py
semantic-conventions/src/opentelemetry/semconv/templating/code.py
semantic-conventions/src/opentelemetry/semconv/templating/markdown/__init__.py
semantic-conventions/src/tests/conftest.py
semantic-conventions/src/tests/semconv/model/test_correct_parse.py
semantic-conventions/src/tests/semconv/model/test_error_detection.py
semantic-conventions/src/tests/semconv/model/test_semantic_convention.py
semantic-conventions/src/tests/semconv/model/test_semantic_convention_units.py
semantic-conventions/src/tests/semconv/model/test_utils.py
semantic-conventions/src/tests/semconv/templating/test_markdown.py

This is the last linter, now we have parity with opentelemetry-python.

Add isort to ensure consistent ordering of imports.

---

semantic-conventions/CHANGELOG.md
semantic-conventions/src/opentelemetry/semconv/templating/markdown/__init__.py
semantic-conventions/src/opentelemetry/semconv/version.py
semantic-conventions/src/tests/data/markdown/sampling_relevant/expected.md
semantic-conventions/src/tests/data/markdown/sampling_relevant/general.yaml
semantic-conventions/src/tests/data/markdown/sampling_relevant/http.yaml
semantic-conventions/src/tests/data/markdown/sampling_relevant/input.md
semantic-conventions/src/tests/data/markdown/sampling_relevant/span-general.md
semantic-conventions/src/tests/semconv/templating/test_markdown.py
semantic-conventions/syntax.md

Related to https://github.com/open-telemetry/opentelemetry-specification/pull/1916

Support sampling_relevant attributes

---

schemas/Dockerfile

This was incorrectly added to the Dockerfile and causes problems when running since there is normally no such user on the host machine. This is not necessary, so removing.

Remove unnecessary USER directive from schema check Dockerfile

---

.github/CODEOWNERS

@thisthat is no longer involved in OTel and does not have the capacity to review and build-tools PRs, so let's take him off the list of approvers.
Thank you for your contributions in the past, @thisthat! 😊

Update CODEOWNERS for semantic-conventions

---

semantic-conventions/src/opentelemetry/semconv/model/semantic_attribute.py
semantic-conventions/src/opentelemetry/semconv/model/semantic_convention.py
semantic-conventions/src/opentelemetry/semconv/templating/markdown/__init__.py
semantic-conventions/src/tests/data/markdown/ref/expected.md
semantic-conventions/src/tests/data/markdown/ref/general.yaml
semantic-conventions/src/tests/data/markdown/ref/rpc.yaml

If the requirement level is not overridden when referencing an attribute, we should reuse the original one

Apply requirement level and msg of referenced attribute by default

---

.github/workflows/semconvgen.yml

Required for dependabot's open-telemetry/build-tools#100

Workflows: Specify python version: setup-python@v4 compat.

---

semantic-conventions/CHANGELOG.md
semantic-conventions/README.md
semantic-conventions/src/opentelemetry/semconv/main.py
semantic-conventions/src/opentelemetry/semconv/templating/code.py
semantic-conventions/src/tests/data/jinja/metrics/expected_no_whitespace.java
semantic-conventions/src/tests/data/jinja/metrics/expected_trim_whitespace_enabled.java
semantic-conventions/src/tests/data/jinja/metrics/units_template_trim_whitespace_enabled
semantic-conventions/src/tests/semconv/templating/test_code.py

Sometimes it might be desired to customize the Jinja Environment. For example, it might be useful to enable the features in Jinja to [strip/trim blocks to make it easier to control whitespace](https://jinja.palletsprojects.com/en/3.1.x/templates/#whitespace-control) rendering in templates.
This PR adds a possibility to ~~pass multiple parameters (similar as the params that are fed into the template)which are passed into the `jinja2.Environment` as is.~~ provide a new flag `--trim-whitespace` which enables both `trim_blocks` and `lstrip_blocks` in the Jinja environment
I came into this, while working on using the semconv code tool to generate the code files for the conventions in .NET: https://github.com/open-telemetry/opentelemetry-dotnet/pull/2069
It proved very challenging to manage the …

Allow customising the `jinja2.Environment`

---

semantic-conventions/src/opentelemetry/semconv/model/semantic_convention.py

https://github.com/open-telemetry/build-tools/pull/107 established that this warning is intended to advise users to set the type for a group. This PR is to:
> _From `syntax.md`_...
> - `type`, optional enum, defaults to `span` (with a warning if not present).
I would love to add some language to this ☝🏻 section of the `syntax.md` document, further explaining what a group's `type` field means. Unfortunately, I don't know what it means. Could anyone suggest some further explanation?

Clarify warning & fix line number

---

CONTRIBUTING.md

Add release instructions to CONTRIBUTING.md

---

semantic-conventions/CHANGELOG.md
semantic-conventions/semconv.schema.json
semantic-conventions/src/opentelemetry/semconv/model/semantic_convention.py
semantic-conventions/src/tests/data/markdown/scope/expected.md
semantic-conventions/src/tests/data/markdown/scope/input.md
semantic-conventions/src/tests/data/markdown/scope/scope.yaml
semantic-conventions/src/tests/data/yaml/scope.yaml
semantic-conventions/src/tests/semconv/model/test_correct_parse.py
semantic-conventions/src/tests/semconv/templating/test_markdown.py
semantic-conventions/syntax.md

Part of https://github.com/open-telemetry/opentelemetry-specification/issues/2682
Addresses this comment: https://github.com/open-telemetry/opentelemetry-specification/pull/2702#discussion_r933096178
This adds "scope" as a semantic convention type.
cc @joaopgrassi

Add scope semantic conventions as a type

---

semantic-conventions/.pylintrc
semantic-conventions/dev-requirements.txt
semantic-conventions/src/opentelemetry/semconv/main.py
semantic-conventions/src/opentelemetry/semconv/model/exceptions.py
semantic-conventions/src/opentelemetry/semconv/model/semantic_attribute.py
semantic-conventions/src/opentelemetry/semconv/model/semantic_convention.py
semantic-conventions/src/opentelemetry/semconv/model/utils.py
semantic-conventions/src/opentelemetry/semconv/templating/code.py
semantic-conventions/src/opentelemetry/semconv/templating/markdown/__init__.py
semantic-conventions/src/tests/semconv/model/test_correct_parse.py

Build scripts now use Python 3.11, but old pylint does not work with it:
https://github.com/open-telemetry/build-tools/actions/runs/3439733856/jobs/5737365717
This change updates pylint and also fixes new errors from it.

Make pylint work with python 3.11 and fix new errors

---

semantic-conventions/CONTRIBUTING.md
semantic-conventions/README.md

This PR formalizes the build system used to generate the semantic convention generator (semconvgen). 
At least, I think it does.  I'd greatly appreciate if someone who's ran a release before could review this one.
Related issue: https://github.com/open-telemetry/build-tools/issues/119

Add a detailed CONTRIBUTING guide for semantic-conventions build-tools

---

semantic-conventions/semconv.schema.json
semantic-conventions/src/opentelemetry/semconv/model/semantic_attribute.py
semantic-conventions/src/opentelemetry/semconv/templating/markdown/__init__.py
semantic-conventions/src/tests/data/markdown/empty/expected.md
semantic-conventions/src/tests/data/markdown/empty/input.md
semantic-conventions/src/tests/data/markdown/metrics_tables/expected.md
semantic-conventions/src/tests/data/markdown/missing_end_tag/input.md
semantic-conventions/src/tests/data/markdown/ref/expected.md
semantic-conventions/src/tests/data/markdown/ref/rpc.yaml
semantic-conventions/src/tests/data/yaml/errors/wrong_multiple_requirement_levels.yaml
semantic-conventions/src/tests/data/yaml/metrics.yaml
semantic-conventions/syntax.md

Based on suggestion by @arminru and others.
Needed before we mark [attribute-requirement-level.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md) as stable (which is needed before we mark HTTP semantic conventions stable, see https://github.com/open-telemetry/opentelemetry-specification/issues/3219)

Rename Optional attribute requirement level to Opt-In

---

semantic-conventions/src/opentelemetry/semconv/main.py
semantic-conventions/src/opentelemetry/semconv/model/semantic_convention.py

Alternative approach to #156
Usage diff: 
Java generates all semconv except resources into one file
```diff
docker run --rm \
-v ${SCRIPT_DIR}/opentelemetry-specification/semantic_conventions:/source \
-v ${SCRIPT_DIR}/templates:/templates \
-v ${ROOT_DIR}/semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/:/output \
otel/semconvgen:$GENERATOR_VERSION \
-  --exclude resource/** \
+  --only span,event,attribute_group,scope \
-f /source code \
...
```
Resources:
```diff
docker run --rm \
- -v ${SCRIPT_DIR}/opentelemetry-specification/semantic_conventions/resource/:/source \
+ -v ${SCRIPT_DIR}/opentelemetry-specification/semantic_conventions:/source \
-v ${SCRIPT_DIR}/templates:/templates \
-v ${ROOT_DIR}/semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/:/output …
```

Allow multiple semconv in --only flag

---

semantic-conventions/src/opentelemetry/semconv/templating/markdown/__init__.py
semantic-conventions/src/tests/data/markdown/metrics_tables/expected.md
semantic-conventions/src/tests/data/yaml/metrics.yaml

resolves #167, part of #15.
This only targets metrics, as for that we have a well-defined way to render in markdown (`to_markdown_metric_table`). For other convention types such as `resource` we don't have a well-defined markdown "template" on how we want them to look so I left it for now. 
cc @trask

Render notes on metric semconv tables

---

.github/CODEOWNERS

Quite often changes to our semantic conventions tooling originate from requests and discussions in https://github.com/open-telemetry/semantic-conventions, so I think it would make sense if @open-telemetry/specs-semconv-approvers would also co-own the tooling here. They usually have most of the context and are the front-line stakeholders in semconv tooling.

Add semantic convention approvers to CODEOWNERS

---

semantic-conventions/CHANGELOG.md
semantic-conventions/src/opentelemetry/semconv/model/semantic_attribute.py
semantic-conventions/src/tests/data/markdown/stability/badges_expected.md
semantic-conventions/src/tests/semconv/model/test_correct_parse.py

Change default stability level to experimental

---

semantic-conventions/CHANGELOG.md
semantic-conventions/semconv.schema.json
semantic-conventions/src/opentelemetry/semconv/model/semantic_attribute.py
semantic-conventions/src/opentelemetry/semconv/model/semantic_convention.py
semantic-conventions/src/opentelemetry/semconv/templating/code.py
semantic-conventions/src/opentelemetry/semconv/templating/markdown/__init__.py
semantic-conventions/src/tests/data/jinja/attribute_templates/expected.java
semantic-conventions/src/tests/data/jinja/attribute_templates/template
semantic-conventions/src/tests/data/markdown/attribute_templates/attribute_templates.yaml
semantic-conventions/src/tests/data/markdown/attribute_templates/expected.md
semantic-conventions/src/tests/data/markdown/attribute_templates/input.md
semantic-conventions/src/tests/data/yaml/attr_templates_code/attribute_templates.yml
semantic-conventions/src/tests/data/yaml/attribute_templates.yml
semantic-conventions/src/tests/semconv/model/test_semantic_attribute.py
semantic-conventions/src/tests/semconv/templating/test_code.py
semantic-conventions/src/tests/semconv/templating/test_markdown.py
semantic-conventions/syntax.md

In the semantic conventions we have `template`-style attributes in some places.
Examples are:
- [HTTP request and response headers](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/#http-request-and-response-headers): `http.request.header.<key>`, `http.response.header.<key>`
- [Elasticsearch path parts](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/elasticsearch.md#url-path-parts): `db.elasticsearch.path_parts.<key>` 
This kind of attributes could not be included in the model `.yml` files yet, and thus could not be included in table generation.
This PR proposes a fix that enables definition of `template`-style attributes in the YAML files and corresponding table generation.
Template-style attributes (i.e. that do not result in a …

Enable rendering of "template" attributes in table generation

---

semantic-conventions/CHANGELOG.md
semantic-conventions/semconv.schema.json

The `conditionally_required` option for `requirement_level` has an error in the schema.json. This causes the vscode extension to flag an error when there is none. Here's an example from http-common: 
The fix is simply to change the properties to match `conditionally_required`.

Fixed conditionally_required requirement_level.

---

semantic-conventions/src/opentelemetry/semconv/templating/markdown/__init__.py
semantic-conventions/src/tests/data/markdown/omit_requirement_level/expected.md
semantic-conventions/src/tests/data/markdown/omit_requirement_level/http.yaml
semantic-conventions/src/tests/data/markdown/omit_requirement_level/input.md
semantic-conventions/src/tests/semconv/templating/test_markdown.py

When rendering attributes tables outside specific semantic conventions (e.g. in an attributes dictionary), we need a way to omit rendering the `requirement_level` column in the table.
See this proposal:
- https://github.com/open-telemetry/semantic-conventions/issues/197
This PR introduces an optional `omit_requirement_level` parameter in the markdown `semconv_selector` syntax that indicates the table rendering logic to omit rendering the `requirement_level` column in the corresponding attributes table.

Added `omit_requirement_level` option for markdown table rendering

---

semantic-conventions/CHANGELOG.md
semantic-conventions/src/opentelemetry/semconv/model/semantic_convention.py
semantic-conventions/src/opentelemetry/semconv/templating/markdown/__init__.py
semantic-conventions/src/tests/data/markdown/deprecated/expected.md
semantic-conventions/src/tests/data/markdown/event/expected.md
semantic-conventions/src/tests/data/markdown/extend_constraint/expected.md
semantic-conventions/src/tests/data/markdown/extend_grandparent/database.yaml
semantic-conventions/src/tests/data/markdown/extend_grandparent/expected.md
semantic-conventions/src/tests/data/markdown/extend_grandparent/input.md
semantic-conventions/src/tests/data/markdown/include/expected.md
semantic-conventions/src/tests/data/markdown/multiple/expected.md
semantic-conventions/src/tests/data/markdown/multiple_enum/expected.md
semantic-conventions/src/tests/data/markdown/omit_requirement_level/expected.md
semantic-conventions/src/tests/data/markdown/parameter_full/expected.md
semantic-conventions/src/tests/data/markdown/parameter_remove_constraint/expected.md
semantic-conventions/src/tests/data/markdown/parameter_tag/expected.md
semantic-conventions/src/tests/data/markdown/parameter_tag_empty/expected.md
semantic-conventions/src/tests/data/markdown/ref/expected.md
semantic-conventions/src/tests/data/markdown/sampling_relevant/expected.md
semantic-conventions/src/tests/data/markdown/single/expected.md
semantic-conventions/src/tests/data/markdown/sorting/expected.md
semantic-conventions/src/tests/data/markdown/sorting/input.md
semantic-conventions/src/tests/data/markdown/sorting/input.yaml
semantic-conventions/src/tests/data/markdown/stability/badges_expected.md
semantic-conventions/src/tests/data/markdown/stability/labels_expected.md
semantic-conventions/src/tests/semconv/model/test_correct_parse.py
semantic-conventions/src/tests/semconv/templating/test_markdown.py

How attributes are added to semconv is an implementation detail, rendered markdown should not depend on it.
This change sorts attributes in final md table alphabetically. 
This would also reduce diffs in semconv and help us review uninteresting changes when hierarchy refactorings cause massive changes because of attributes moving in the table.

Sort attributes by name, not by source

---

semantic-conventions/src/opentelemetry/semconv/model/semantic_convention.py
semantic-conventions/src/tests/data/markdown/attribute_templates/attribute_templates.yaml
semantic-conventions/src/tests/data/markdown/attribute_templates/expected.md
semantic-conventions/src/tests/data/markdown/attribute_templates/input.md
semantic-conventions/src/tests/semconv/model/test_correct_parse.py

In https://github.com/open-telemetry/build-tools/pull/186 there was an oversight that template-type attributes cannot be referenced in other semantic conventions.
This PR fixes this bug and extends the corresponding test with a referenced template attribute.

Fix referencing template attributes

---

.github/workflows/semconvgen.yml

This should allow @lmolkova's changes from https://github.com/open-telemetry/build-tools/pull/243 to be published under a specific tag on Docker Hub.
cc @open-telemetry/specs-semconv-maintainers

Update semconvgen.yml workflow to run on feature/* branches

---

semantic-conventions/README.md
semantic-conventions/src/opentelemetry/semconv/templating/code.py
semantic-conventions/src/tests/semconv/templating/test_code.py

Related to #242 - "File names should follow per-language pattern"
When outputting multiple files, we allow `--output` to be evaluated as its own jinja template.   This template would have the following values:
- `prefix`
- `pascal_prefix`
- `camel_prefix`
- `snake_prefix`
This should allow language authors to customize filenames as they need for language conventions.

Allow --output to be templatized when generating multiple files.

---

semantic-conventions/src/opentelemetry/semconv/model/semantic_convention.py

Fixes checks for https://github.com/open-telemetry/semantic-conventions/pull/985

Added display_name as an allowed property on semconv attribute groups

---

semantic-conventions/CHANGELOG.md
semantic-conventions/semconv.schema.json
semantic-conventions/syntax.md

We're moving schema file to the weaver project (as a part of https://github.com/open-telemetry/build-tools/issues/322 and https://github.com/open-telemetry/semantic-conventions/issues/916).
This PR updates and cleans up schema definition and syntax docs:
- migrate to the latest json-schema version
- require stability on everything
- remove prefix
- remove `allow_custom_values` on enum attributes
- allow deprecation on groups
Some of these properties were removed from build-tools code, others (like `allow_custom_values`) are still supported by the tooling.
Schema is not enforced: removing properties from the schema does not break anything, it will just improve VSCode autocomplete and highlight unknown properties in red.
TODO:

Update schema and syntax

---

protobuf/Dockerfile

Parquet never landed as part of the protobuf code generation ; time to remove it.

Remove parquet from the protobuf build image

---

.github/CODEOWNERS

Fixes:
```
CODEOWNERS errors
Unknown owner on line 16: make sure the team @open-telemetry/specs-approvers exists, is publicly visible, and has write access to the repository
*   @open-telemetry/specs-approvers
```

Update CODEOWNERS to reflect new team handle
